### PR TITLE
[OpenRefine] Add munki and download recipe

### PR DESCRIPTION
**Pull request by cwhits**
Added a recipe for OpenRefine.

```
$ autopkg run OpenRefine.munki.recipe -v
Processing OpenRefine.munki.recipe...
WARNING: OpenRefine.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex 'openrefine-mac-.+\.dmg' among asset(s): openrefine-linux-2.7-rc.1.tar.gz, openrefine-mac-2.7-rc.1.dmg, openrefine-win-2.7-rc.1.zip
GitHubReleasesInfoProvider: Selected asset 'openrefine-mac-2.7-rc.1.dmg' from release 'OpenRefine v2.7 Release Candidate 1'
URLDownloader
URLDownloader: Storing new Last-Modified header: Sat, 11 Feb 2017 14:04:05 GMT
URLDownloader: Storing new ETag header: "58c85126b7419a1fca87d6e0941fe8aa"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.OpenRefine/downloads/openrefine-mac-2.7-rc.1.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Code signature verification disabled for this recipe run.
MunkiImporter
MunkiImporter: Copied pkginfo to /munki/pkgsinfo/apps/OpenRefine/OpenRefine-2.7-rc.1.plist
MunkiImporter: Copied pkg to /munki/pkgs/apps/OpenRefine/openrefine-mac-2.7-rc.1.dmg
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.OpenRefine/receipts/OpenRefine.munki-receipt-20170222-174635.plist

The following new items were imported into Munki:
    Name        Version   Catalogs  Pkginfo Path                               Pkg Repo Path
    ----        -------   --------  ------------                               -------------
    OpenRefine  2.7-rc.1  testing   apps/OpenRefine/OpenRefine-2.7-rc.1.plist  apps/OpenRefine/openrefine-mac-2.7-rc.1.dmg

The following new items were downloaded:
    Download Path
    -------------
    /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.OpenRefine/downloads/openrefine-mac-2.7-rc.1.dmg
```

### CODE REVIEW

**Comment by cwhits** [comment]
Oh yeah, I added `CodeSignatureVerification` in case they decide to start code signing again. 2.6 rc1 was code signed and I filed an issue with them

I set
```
<key>DISABLE_CODE_SIGNATURE_VERIFICATION</key>
<true/>
```
So it can just be reenabled if/when they code sign again.

**Comment by cwhits** [comment]
See: https://github.com/OpenRefine/OpenRefine/issues/1174

**Comment by cwhits** [comment]
I removed `codesignatureverification` because they didn't use the same cert as last time and it's a self-signed cert so it's likely to break again in the future.

It works

**Comment by n8felton** [comment]
Are you sure this time? lol

**Comment by cwhits** [comment]
it wasn't my fault!

**Pull request merged**
