### PR TITLE
Modified Weka download recipe to allow downloading stable or develope…

### PR DESCRIPTION
**Pull request by LordShellby**
…r and Intel or ARM64 versions

Scrapes the Weka download page to find the correct download URL. Also a minor change to the Munki recipe to account for name change to the downloaded file.

### Output of `autopkg run -vvvv`
```
Processing Weka.munki.recipe...
WARNING: Weka.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'ARCHITECTURE': 'intel',
 'AUTOPKG_VERSION': '2.4.1',
 'DOWNLOAD_VERSION': 'stable',
 'GIT_PATH': '/Library/Developer/CommandLineTools/usr/bin/git',
 'MUNKI_CATEGORY': 'Math & Science',
 'MUNKI_REPO': '/Volumes/eaxer-hd/nginx/munki/munki_repo',
 'MUNKI_REPO_SUBDIR': 'apps/Weka',
 'NAME': 'Weka',
 'PARENT_RECIPES': ['/Users/lordshellby/Development/autopkg-recipes/felton/git-versions/Weka.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka',
 'RECIPE_DIR': '/Users/lordshellby/Development/autopkg-recipes/felton/git-versions',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/lordshellby/Development/autopkg-recipes/felton/git-versions/Weka.munki.recipe',
 'RECIPE_REPOS': {'/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.48kRAM-recipes': {'URL': 'https://github.com/autopkg/48kRAM-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes': {'URL': 'https://github.com/autopkg/apettinen-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes': {'URL': 'https://github.com/autopkg/bochoven-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes': {'URL': 'https://github.com/autopkg/gerardkok-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes': {'URL': 'https://github.com/autopkg/grahampugh-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes': {'URL': 'https://github.com/autopkg/jazzace-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes': {'URL': 'https://github.com/autopkg/jessepeterson-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.natewalck-recipes': {'URL': 'https://github.com/autopkg/natewalck-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes': {'URL': 'https://github.com/autopkg/nstrauss-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nzmacgeek-recipes': {'URL': 'https://github.com/autopkg/nzmacgeek-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.orchard-recipes': {'URL': 'https://github.com/autopkg/orchard-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes': {'URL': 'https://github.com/autopkg/smithjw-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes': {'URL': 'https://github.com/autopkg/wardsparadox-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes': {'URL': 'https://github.com/autopkg/ygini-recipes.git'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nzmacgeek-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.orchard-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.natewalck-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.48kRAM-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes',
                        ''],
 'SEARCH_URL': 'https://waikato.github.io/weka-wiki/downloading_weka/',
 'pkginfo': {'catalogs': ['testing'],
             'category': 'Math & Science',
             'description': 'Weka is a collection of machine learning '
                            'algorithms for solving real-world data mining '
                            'problems. It is written in Java and runs on '
                            'almost any platform. The algorithms can either be '
                            'applied directly to a dataset or called from your '
                            'own Java code.',
             'developer': 'University of Waikato',
             'display_name': 'Weka',
             'name': 'Weka',
             'unattended_install': True},
 'verbose': 4}
URLTextSearcher
{'Input': {'re_flags': ['DOTALL'],
           're_pattern': 'id=\\"stable-version\\".+?mac-os-intel-processors.+?(https://prdownloads\\.sourceforge\\.net/weka/weka.+?osx\\.dmg)',
           'url': 'https://waikato.github.io/weka-wiki/downloading_weka/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://waikato.github.io/weka-wiki/downloading_weka/']
URLTextSearcher: Found matching text (match): https://prdownloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg
{'Output': {'match': 'https://prdownloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg'}}
URLDownloader
{'Input': {'url': 'https://prdownloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Curl command: ['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://prdownloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg', '--fail', '--output', '/Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/downloads/tmp009_zrre', '--header', 'If-None-Match: "61ff4d1b-aead687"', '--header', 'If-Modified-Since: Sun, 06 Feb 2022 04:22:51 GMT']
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/downloads/weka-3-8-6-azul-zulu-osx.dmg
{'Output': {'pathname': '/Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/downloads/weka-3-8-6-azul-zulu-osx.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
MunkiImporter
{'Input': {'MUNKI_REPO': '/Volumes/eaxer-hd/nginx/munki/munki_repo',
           'pkg_path': '/Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/downloads/weka-3-8-6-azul-zulu-osx.dmg',
           'pkginfo': {'catalogs': ['testing'],
                       'category': 'Math & Science',
                       'description': 'Weka is a collection of machine '
                                      'learning algorithms for solving '
                                      'real-world data mining problems. It is '
                                      'written in Java and runs on almost any '
                                      'platform. The algorithms can either be '
                                      'applied directly to a dataset or called '
                                      'from your own Java code.',
                       'developer': 'University of Waikato',
                       'display_name': 'Weka',
                       'name': 'Weka',
                       'unattended_install': True},
           'repo_subdirectory': 'apps/Weka'}}
MunkiImporter: No value supplied for MUNKI_REPO_PLUGIN, setting default value of: FileRepo
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:         plugin: FileRepo
MunkiImporter:           repo: /Volumes/eaxer-hd/nginx/munki/munki_repo
MunkiImporter: Copied pkginfo to: /Volumes/eaxer-hd/nginx/munki/munki_repo/pkgsinfo/apps/Weka/Weka-3.8.6.plist
MunkiImporter:            pkg to: /Volumes/eaxer-hd/nginx/munki/munki_repo/pkgs/apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg
{'Output': {'munki_importer_summary_result': {'data': {'catalogs': 'testing',
                                                       'icon_repo_path': '',
                                                       'name': 'Weka',
                                                       'pkg_repo_path': 'apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
                                                       'pkginfo_path': 'apps/Weka/Weka-3.8.6.plist',
                                                       'version': '3.8.6'},
                                              'report_fields': ['name',
                                                                'version',
                                                                'catalogs',
                                                                'pkginfo_path',
                                                                'pkg_repo_path',
                                                                'icon_repo_path'],
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'imported into '
                                                              'Munki:'},
            'munki_info': {'_metadata': {'created_by': 'lordshellby',
                                         'creation_date': datetime.datetime(2022, 5, 15, 11, 28, 10),
                                         'munki_version': '5.6.4.4406',
                                         'os_version': '12.3.1'},
                           'autoremove': False,
                           'catalogs': ['testing'],
                           'category': 'Math & Science',
                           'description': 'Weka is a collection of machine '
                                          'learning algorithms for solving '
                                          'real-world data mining problems. It '
                                          'is written in Java and runs on '
                                          'almost any platform. The algorithms '
                                          'can either be applied directly to a '
                                          'dataset or called from your own '
                                          'Java code.',
                           'developer': 'University of Waikato',
                           'display_name': 'Weka',
                           'installer_item_hash': '282d5ff81960d1ae43ee6e4e8eaa7ae8c341666a214e859728e15214af80383b',
                           'installer_item_location': 'apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
                           'installer_item_size': 178869,
                           'installer_type': 'copy_from_dmg',
                           'installs': [{'CFBundleIdentifier': 'weka.gui',
                                         'CFBundleName': 'weka-3.8.6',
                                         'CFBundleShortVersionString': '3.8.6',
                                         'CFBundleVersion': '3.8.6',
                                         'minosversion': '10.11',
                                         'path': '/Applications/weka-3.8.6.app',
                                         'type': 'application',
                                         'version_comparison_key': 'CFBundleShortVersionString'}],
                           'items_to_copy': [{'destination_path': '/Applications',
                                              'source_item': 'weka-3.8.6.app'}],
                           'minimum_os_version': '10.11',
                           'name': 'Weka',
                           'unattended_install': True,
                           'uninstall_method': 'remove_copied_items',
                           'uninstallable': True,
                           'version': '3.8.6'},
            'munki_repo_changed': True,
            'pkg_repo_path': '/Volumes/eaxer-hd/nginx/munki/munki_repo/pkgs/apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
            'pkginfo_repo_path': '/Volumes/eaxer-hd/nginx/munki/munki_repo/pkgsinfo/apps/Weka/Weka-3.8.6.plist'}}
{'ARCHITECTURE': 'intel',
 'AUTOPKG_VERSION': '2.4.1',
 'CHECK_FILESIZE_ONLY': False,
 'DOWNLOAD_VERSION': 'stable',
 'GIT_PATH': '/Library/Developer/CommandLineTools/usr/bin/git',
 'MUNKILIB_DIR': '/usr/local/munki',
 'MUNKI_CATEGORY': 'Math & Science',
 'MUNKI_REPO': '/Volumes/eaxer-hd/nginx/munki/munki_repo',
 'MUNKI_REPO_PLUGIN': 'FileRepo',
 'MUNKI_REPO_SUBDIR': 'apps/Weka',
 'NAME': 'Weka',
 'PARENT_RECIPES': ['/Users/lordshellby/Development/autopkg-recipes/felton/git-versions/Weka.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka',
 'RECIPE_DIR': '/Users/lordshellby/Development/autopkg-recipes/felton/git-versions',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/lordshellby/Development/autopkg-recipes/felton/git-versions/Weka.munki.recipe',
 'RECIPE_REPOS': {'/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.48kRAM-recipes': {'URL': 'https://github.com/autopkg/48kRAM-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes': {'URL': 'https://github.com/autopkg/apettinen-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes': {'URL': 'https://github.com/autopkg/bochoven-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes': {'URL': 'https://github.com/autopkg/gerardkok-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes': {'URL': 'https://github.com/autopkg/grahampugh-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes': {'URL': 'https://github.com/autopkg/jazzace-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes': {'URL': 'https://github.com/autopkg/jessepeterson-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.natewalck-recipes': {'URL': 'https://github.com/autopkg/natewalck-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes': {'URL': 'https://github.com/autopkg/nstrauss-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nzmacgeek-recipes': {'URL': 'https://github.com/autopkg/nzmacgeek-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.orchard-recipes': {'URL': 'https://github.com/autopkg/orchard-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes': {'URL': 'https://github.com/autopkg/smithjw-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes': {'URL': 'https://github.com/autopkg/wardsparadox-recipes.git'},
                  '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes': {'URL': 'https://github.com/autopkg/ygini-recipes.git'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nzmacgeek-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.orchard-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.natewalck-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.48kRAM-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes',
                        '/Users/lordshellby/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes',
                        ''],
 'SEARCH_URL': 'https://waikato.github.io/weka-wiki/downloading_weka/',
 'download_changed': False,
 'etag': '',
 'force_munki_repo_lib': False,
 'icon_repo_path': '',
 'last_modified': '',
 'match': 'https://prdownloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg',
 'munki_importer_summary_result': {'data': {'catalogs': 'testing',
                                            'icon_repo_path': '',
                                            'name': 'Weka',
                                            'pkg_repo_path': 'apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
                                            'pkginfo_path': 'apps/Weka/Weka-3.8.6.plist',
                                            'version': '3.8.6'},
                                   'report_fields': ['name',
                                                     'version',
                                                     'catalogs',
                                                     'pkginfo_path',
                                                     'pkg_repo_path',
                                                     'icon_repo_path'],
                                   'summary_text': 'The following new items '
                                                   'were imported into Munki:'},
 'munki_info': {'_metadata': {'created_by': 'lordshellby',
                              'creation_date': datetime.datetime(2022, 5, 15, 11, 28, 10),
                              'munki_version': '5.6.4.4406',
                              'os_version': '12.3.1'},
                'autoremove': False,
                'catalogs': ['testing'],
                'category': 'Math & Science',
                'description': 'Weka is a collection of machine learning '
                               'algorithms for solving real-world data mining '
                               'problems. It is written in Java and runs on '
                               'almost any platform. The algorithms can either '
                               'be applied directly to a dataset or called '
                               'from your own Java code.',
                'developer': 'University of Waikato',
                'display_name': 'Weka',
                'installer_item_hash': '282d5ff81960d1ae43ee6e4e8eaa7ae8c341666a214e859728e15214af80383b',
                'installer_item_location': 'apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
                'installer_item_size': 178869,
                'installer_type': 'copy_from_dmg',
                'installs': [{'CFBundleIdentifier': 'weka.gui',
                              'CFBundleName': 'weka-3.8.6',
                              'CFBundleShortVersionString': '3.8.6',
                              'CFBundleVersion': '3.8.6',
                              'minosversion': '10.11',
                              'path': '/Applications/weka-3.8.6.app',
                              'type': 'application',
                              'version_comparison_key': 'CFBundleShortVersionString'}],
                'items_to_copy': [{'destination_path': '/Applications',
                                   'source_item': 'weka-3.8.6.app'}],
                'minimum_os_version': '10.11',
                'name': 'Weka',
                'unattended_install': True,
                'uninstall_method': 'remove_copied_items',
                'uninstallable': True,
                'version': '3.8.6'},
 'munki_repo_changed': True,
 'pathname': '/Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/downloads/weka-3-8-6-azul-zulu-osx.dmg',
 'pkg_path': '/Volumes/eaxer-hd/nginx/munki/munki_repo/pkgs/apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
 'pkg_repo_path': '/Volumes/eaxer-hd/nginx/munki/munki_repo/pkgs/apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmg',
 'pkginfo': {'catalogs': ['testing'],
             'category': 'Math & Science',
             'description': 'Weka is a collection of machine learning '
                            'algorithms for solving real-world data mining '
                            'problems. It is written in Java and runs on '
                            'almost any platform. The algorithms can either be '
                            'applied directly to a dataset or called from your '
                            'own Java code.',
             'developer': 'University of Waikato',
             'display_name': 'Weka',
             'name': 'Weka',
             'unattended_install': True},
 'pkginfo_repo_path': '/Volumes/eaxer-hd/nginx/munki/munki_repo/pkgsinfo/apps/Weka/Weka-3.8.6.plist',
 'prefetch_filename': False,
 're_flags': ['DOTALL'],
 're_pattern': 'id=\\"stable-version\\".+?mac-os-intel-processors.+?(https://prdownloads\\.sourceforge\\.net/weka/weka.+?osx\\.dmg)',
 'repo_subdirectory': 'apps/Weka',
 'result_output_var_name': 'match',
 'url': 'https://prdownloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg',
 'verbose': 4}
Receipt written to /Users/lordshellby/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/receipts/Weka.munki-receipt-20220515-122827.plist

The following new items were imported into Munki:
    Name  Version  Catalogs  Pkginfo Path                Pkg Repo Path                                 Icon Repo Path
    ----  -------  --------  ------------                -------------                                 --------------
    Weka  3.8.6    testing   apps/Weka/Weka-3.8.6.plist  apps/Weka/weka-3-8-6-azul-zulu-osx-3.8.6.dmglordshellby
```

### CODE REVIEW

**Comment by fuzzylogiq** [comment]
bump?

**Comment by n8felton** [comment]
@LordShellby Can you check the box for 'Allow edits from maintainers', I'd like to push up some lint/format changes to the recipes before merging.

**Comment by n8felton** [comment]
:natepalm: sorry for the close and re-open, tap-to-click apparently decided to fire on the "Close with comment" button instead of the "Comment" button...

**Comment by n8felton** [comment]
I can't seem to push to LordShellby/master ¯\_(ツ)_/¯

Accepting this, and I'll do a separate commit with the linting/formatting.

Thanks for the work on this!

**Comment by chelming** [comment]
hey @n8felton, you dropped this: `\`

**Comment by LordShellby** [comment]
No problem. Thanks for sorting out the linting/formatting :)

**Pull request merged**
